dataset_repo_id: objones25/pokemon-frames
frozen_encoder_repo_id: objones25/pokemon-contrastive-encoder
val_video_ids: [D1SrSFZrV7A, YW29l3jJXr4]
pretrained: true
batch_size: 1024
num_workers: 8
shuffle_buffer_size: 10000
seed: 0
learning_rate: 0.0004
warmup_steps: 500
weight_decay: 0.000001
temperature: 0.1
max_epochs: 100
checkpoint_interval_steps: 1000
network_volume_checkpoint_dir: /runpod-volume/contrastive_pretrain/checkpoints
